import React from "react"
import ReactDOM from "react-dom/client"
// entry.tsx is generated by run.mjs when it mounts a zip.
import Mounted from "./mounted/entry"

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <Mounted />
  </React.StrictMode>
)
